### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by MoRaad97** [MoRaad97/recipe-app#11]
### 2. @MoRaad97 

Thanks,

**Comment by KDlamini** [comment]
### Hi team @MoRaad97, @kelomo2502 🙋‍♀️,  

Great job so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Tasks have well-detailed descriptions
✔️  Cards are assigned to team members fairly

## Required Changes ♻️
 
Your Kanban  Board should have a total of four columns as listed below:

* To Do
* In Progress
* In Review
* Done

You are missing the `In Review` column. Kindly add it, the result should look like this:

![image](https://user-images.githubusercontent.com/38088818/196162864-f409fb94-4fa0-4b7f-8d8b-71fd57ab2fea.png)


Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MoRaad97** [comment]
Hi @KDlamini 
Thanks for reminding us will work on adding the missing column.

**Comment by FrederickMih** [comment]
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Kanban board has the required number of columns
- The issues have a title and summary :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
